apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: vovhubdoc/python-app:27b55138b7baa426e598fbb2f4f662a8d8318c7a
        ports:
        - containerPort: 5000
